### ISSUE TITLE
use github workflow matrix for  notebook tests

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/utils#24]

**Comment by adampingel** [comment]
@ink-pad noticed this about GPU runners (from July): https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/

**Comment by bjhargrave** [comment]
> noticed this about GPU runners

Those are paid-only. So we cannot use them for no-cost.

**Comment by bjhargrave** [comment]
See the following PRs for the implementation of this across the cookbook repos.

https://github.com/ibm-granite-community/granite-legal-cookbook/pull/22
https://github.com/ibm-granite-community/granite-snack-cookbook/pull/72
https://github.com/ibm-granite-community/granite-code-cookbook/pull/154
https://github.com/ibm-granite-community/granite-finance-cookbook/pull/8
https://github.com/ibm-granite-community/granite-timeseries-cookbook/pull/25
